#! /usr/bin/env node

/*
 * Simple script to remove duplicate files from downloads
 * 	removes all files in the form of * (number).extension
 * 	specifically targets stupid duplicates from chrome
 *
 *	To change the behavior of the script, change the regex
 *	tested in filterPredicate().
 */

let fs = require('fs'),
	process = require('process'),
	chokidar = require('chokidar');

let DOWNLOAD_LOCATION = '/home/bailey/Downloads';
let REGEX = /.* \(\d\).*/;


process.chdir(DOWNLOAD_LOCATION);

chokidar.watch('.').on('add', path => {
	if (REGEX.test(path)) {
		fs.unlinkSync(path); 
		console.log(`removed ${path}`);
	}
});
